version: '3.8'
services:
  matter-server:
    container_name: matter-server
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    restart: unless-stopped
    privileged: true
    cap_add:
      - ALL
    security_opt:
      - apparmor=unconfined
    volumes:
      - /udobnidom/matter-server/data:/data
      - /run/dbus:/run/dbus:ro # Доступ к D-Bus для связи с адаптером Matter
    network_mode: host # Использует сетевой стек хоста для обнаружения устройств
    # Порт 5580 будет доступен на IP-адресе хоста
